# **Encuestas** {#encuesta}

## Definiciones y problemas generales

Los alojamientos turísticos, es decir todos aquellos establecimientos que regular u ocasionalmente ofrecen hospedaje nocturno a los turistas, son un elemento central para el turismo, dada la importancia que revisten tanto para los visitantes como para la industria turística misma. Por esta razón, los establecimientos de alojamiento turístico ocupan un rol crucial en la medición de la actividad turística y, consecuentemente, las encuestas o relevamientos de ocupación de dichos establecimientos son la fuente de información turística más utilizada en los países y en otros niveles jurisdiccionales (regiones, provincias, departamentos, municipios, etc.).

Las encuestas o relevamientos de establecimientos de alojamiento turístico son un tipo de operativo que se realiza desde la perspectiva de la oferta, es decir, desde la información que brindan los prestadores del servicio. Los objetivos perseguidos pueden ser diversos, dependiendo de los propósitos de las instituciones encargadas de su realización. Sin embargo, en términos generales, estos objetivos suelen ser:

-   conocer, en términos cuantitativos y cualitativos, la oferta de establecimientos que prestan alojamiento turístico;

-   conocer la disponibilidad de plazas y habitaciones;

-   conocer el nivel de ocupación y actividad de los establecimientos que prestan el servicio de alojamiento turístico;

-   cuantificar los pernoctes y viajeros hospedados;

-   clasificar la demanda según origen y permanencia -cantidad de noches que permanecieron alojados-;

-   dimensionar el nivel de empleo generado por esta actividad;

-   analizar las tarifas del sector.

La mayoría de las encuestas de alojamientos turísticos abordan a los establecimientos **pagos**, es decir, aquellos en los que el servicio de alojamiento debe ser abonado; por tanto se deja por fuera a los lugares que ofrecen hospedaje gratuito, dada la mayor dificultad de captación que poseen. Los establecimientos pagos son los hoteles, apart-hoteles, hosterías, hoteles residenciales, departamentos y casas de alquiler temporario, campings, y cualquier otro establecimiento que requiera un pago por el servicio de hospedaje. En cambio, los establecimientos gratuitos comprenden a las casas de familiares y/o amigos, segundas viviendas[^enucestas_alojamientos-1] y otros tipos de alojamientos no convencionales (conventos, predios religiosos -- para retiros espirituales, etc.).

[^enucestas_alojamientos-1]: Las segundas viviendas son aquellos inmuebles propios o alquilados en forma permanente que no constituyen la residencia habitual de un hogar. Cabe recordar que, de acuerdo a la última actualización de las Recomendaciones Internacionales para Estadísticas de Turismo, del año 2008, los viajes, con o sin pernocte, a las segundas viviendas son por definición turísticos, a excepción de cuando el motivo del viaje es ser empleado por una unidad económica con residencia en el destino.

Uno de los inconvenientes asociados a los relevamientos de establecimientos de alojamiento turístico es su escasa comparabilidad en términos de la categorización utilizada para clasificar los establecimientos, tanto en el plano internacional como en los niveles provinciales, departamentales y municipales. Esto se debe a la ausencia de un sistema clasificatorio común que permita el ordenamiento de los diferentes establecimientos dentro de categorías únicas. Según las Recomendaciones Internacionales para Estadísticas de Turismo ([RIET](https://unstats.un.org/unsd/publication/seriesm/seriesm_83rev1s.pdf)) de la Organización Mundial de Turismo (OMT) y la Organización de las Naciones Unidas (ONU), la diversidad de servicios prestados en los diferentes países torna difícil la creación de categorías internacionalmente comparables, razón por la cual alienta a los países a generar sus propias agrupaciones para su aplicación en el plano nacional o sub-nacional. No obstante, esto tampoco resulta sencillo al interior de un país, más aún de uno tan diverso y extenso como Argentina, con usos y costumbres y marcos normativos provinciales muchas veces disímiles.

## Encuestas en Argentina

En Argentina se llevan adelante diversos operativos de alojamientos turísticos, ya sea desde instituciones nacionales, provinciales o municipales.

Desde la esfera nacional, el Ministerio de Turismo y Deportes de la Nación (en adelante MINTURDEP) y el Instituto Nacional de Estadísticas y Censos (INDEC) conducen desde el año 2004, con una periodicidad mensual, la Encuesta de Ocupación Hotelera (EOH). La misma tiene el objetivo de medir el impacto del turismo internacional e interno sobre la actividad de los establecimientos hoteleros y para-hoteleros[^enucestas_alojamientos-2], por medio de los siguientes indicadores: cantidad de plazas y habitaciones disponibles y ocupadas; tasa de ocupación en plazas y habitaciones; número de viajeros hospedados totales y según origen (argentinos, por provincia, o extranjeros, por país o región) y permanencia. La encuesta se realiza sobre una muestra compuesta por establecimientos de 49 de las localidades con mayor oferta hotelera y para-hotelera del país, dentro de las siete regiones turísticas definidas por el MINTURDEP[^enucestas_alojamientos-3]. De este modo, con la EOH es posible realizar dos tipos de estimaciones: 1) resultados para cada una de las 49 localidades contempladas individualmente; 2) resultados regionales (con una cobertura aproximada del 80% de las plazas de cada región) y a nivel total país (con una representatividad del 60% de las plazas totales). Por último, una de las ventajas de este relevamiento radica en que se ejecuta utilizando la misma metodología a lo largo y ancho del país.

[^enucestas_alojamientos-2]: Los tipos de establecimientos relevados son, dentro de los hoteleros, hoteles de 1 a 5 estrellas, apart-hoteles, moteles, hoteles boutique; y, dentro de los para-hoteleros, hoteles residenciales, hoteles sindicales, albergues (o hostels), cabañas (o bungalows), hospedajes, bed&breakfast, hosterías, etc. No obstante, entre estos tipos de alojamiento no se consideran los de tamaño pequeño (con hasta 4 habitaciones o 12 plazas inclusive). Cabe señalar que este operativo excluye a otros alojamientos, como las viviendas de alquiler temporario, los campings, las segundas viviendas y las viviendas de familiares y/o amigos, y otros lugares de alojamiento de menor relevancia, dada la diferencia que presentan en la prestación de servicios con respecto a los establecimientos hoteleros y para-hoteleros.

[^enucestas_alojamientos-3]: Estas regiones son: Ciudad de Buenos Aires, Provincia de Buenos Aires, Córdoba, Litoral (Corrientes, Chaco, Entre Ríos, Formosa, Misiones y Santa Fe), Norte (Catamarca, Jujuy, Salta, Santiago del Estero, Tucumán y La Rioja), Cuyo (Mendoza, San Juan, San Luis) y Patagonia (Chubut, La Pampa, Neuquén, Río Negro, Santa Cruz y Tierra Del Fuego).

Desde una perspectiva provincial/municipal, las instituciones provinciales o municipales de turismo (Secretarías, Direcciones, etc.) también se encargan de medir la actividad de los alojamientos turísticos, mediante relevamientos que pueden ser:

-   coordinados y ejecutados por las instituciones provinciales en todas o algunas localidades de la provincia;

-   coordinados por las instituciones provinciales pero ejecutados por las localidades de la provincia;

-   coordinados y ejecutados por las instituciones municipales.

En el último caso citado, la situación más habitual es que las instituciones provinciales se encarguen de centralizar la información generada por las localidades, para luego producir informes que sinteticen y analicen todos los datos obtenidos, aparte de los informes que elaboran las jurisdicciones locales. Sin embargo, al no existir una misma metodología implementada por las diferentes localidades de una provincia, estos resultados suelen estar expuestos a problemas de consistencia y comparabilidad.

## Estado de situación general de operativos

En este apartado se analizan las situaciones más frecuentes que se presentan cuando se encaran relevamientos a establecimientos de alojamiento que merecen especial atención.

En primer lugar, se observa que los diversos relevamientos provinciales/ departamentales/ municipales tienen distinto **alcance en cuanto a la población bajo estudio**. En efecto, si bien la mayoría de las jurisdicciones abordan a los establecimientos que cuentan con **habilitación comercial,** algunas también estudian a los establecimientos cuya habilitación se encuentra **en trámite**. Adicionalmente, unas pocas provincias/departamentos/localidades incluyen también en su análisis a los establecimientos no habilitados comercialmente. Por otro lado, ya dentro de los establecimientos con habilitación comercial, algunas jurisdicciones acotan su mirada solamente a los establecimientos que han sido inscriptos en la entidad de turismo, mientras que otras abarcan tanto a los inscriptos como no inscriptos en la entidad de turismo[^enucestas_alojamientos-4]. Estas diferencias en el alcance lógicamente conllevan dificultades de comparabilidad entre las diferentes jurisdicciones, sean éstas provinciales, departamentales o locales. Adicionalmente, debe tenerse en cuenta que al excluir del foco de análisis a parte de los establecimientos de alojamiento (p.e. los no habilitados comercialmente o los no inscriptos en las entidades de turismo), se pierde de vista el impacto que los mismos pudieran tener tanto en el sector turístico como en la dinámica económica de la unidad geográfica en cuestión.

[^enucestas_alojamientos-4]: En el proceso de habilitación de un establecimiento de alojamiento turístico, el paso que sigue a la habilitación comercial es la inscripción del establecimiento en la correspondiente entidad de turismo (Secretaría, Sub-Secretaría, Dirección, etc.). Un número considerable de establecimientos omiten esta segunda instancia, quedando fuera de los registros de la entidad de turismo. De este modo, los relevamientos de alojamientos turísticos que analizan únicamente a los establecimientos registrados en los listados de las entidades de turismo, dejan de lado a un conjunto de unidades que podrían tener impacto en el comportamiento del sector.

En relación al **tipo de estudio**, la mayoría de las jurisdicciones intentan tener una cobertura total (censal) de la población objetivo, aunque en muchos casos se llevan adelante estudios muestrales. Sobre este aspecto, una de las situaciones observadas es que la selección de los establecimientos que conformarán la muestra se realiza sin seguir un criterio estadístico[^enucestas_alojamientos-5].De hecho, suele ocurrir que la muestra seleccionada en realidad esté integrada por establecimientos cuyos dueños o responsables sean los más predispuestos a responder, lo cual no constituye un criterio estadístico en la construcción de la muestra. Esto merece especial atención a la hora de analizar los resultados, dado que los datos surgidos de dicha muestra pueden no ser representativos en relación a la población en análisis.

[^enucestas_alojamientos-5]: El muestreo estadístico es aquel en el que todos los elementos de una población (en la mayoría de los casos, los alojamientos habilitados) tienen una probabilidad de selección conocida. En el muestreo al azar simple, que es el método de selección más sencillo, todas las unidades tienen la misma probabilidad de selección.

En lo que al **trabajo de campo** compete, la periodicidad o frecuencia con la que se relevan los datos difiere entre las diferentes provincias, departamentos y/o municipios. En efecto, se observó que la periodicidad de toma del dato puede ser diaria, semanal, quincenal o mensual. A su vez, en los operativos que relevan datos con una frecuencia no diaria, la información recabada puede referir a todos los días del período analizado o solamente a algunos días del mismo. Para este último caso, es preciso considerar si se analizarán los datos únicamente sobre los días relevados o si los resultados obtenidos se expandirán a todos los días comprendidos en el período en cuestión.

En cuanto a **los indicadores**[^enucestas_alojamientos-6], la forma en que son construidos (desde las preguntas del cuestionario hasta la fórmula de cálculo del mismo indicador), difiere entre las distintas jurisdicciones. Por ejemplo, para la construcción del indicador "porcentaje de ocupación en plazas", calculado en casi todos los relevamientos de alojamientos (ya que algunos toman las habitaciones como referencia), los procedimientos son muy disímiles. Al momento del relevamiento, algunas jurisdicciones indagan la cantidad de plazas ocupadas de cada establecimiento cubierto, mientras que otras consultan directamente el porcentaje de ocupación en plazas a cada informante (responsable o dueño del alojamiento). En esta última forma de indagación se presenta el riesgo de que la aproximación al porcentaje alcanzada por el encuestado esté sesgada (por que la percepción del respondente puede estar afectada por lo ocurrido en los últimos días o en otra porción del periodo considerado, cuyo comportamiento puede ser diferente del resto). Por otra parte, puede ocurrir que alguna jurisdicción indague por el "porcentaje de ocupación" sin especificar si se trata de ocupación en plazas o habitaciones, quedando del lado del informante la interpretación de cuál es la unidad a la que refiere la pregunta. Por todo esto, siempre que sea posible, es más recomendable relevar cantidades (de plazas o habitaciones ocupadas) en lugar del porcentaje, dado que encierra menos probabilidades de error al momento de recabar información.

[^enucestas_alojamientos-6]: Los indicadores pueden ser variables concretas (expresadas en la misma pregunta del cuestionario) o variables más complejas y, en ocasiones, con cierto nivel de abstracción. Estas últimas suelen combinar más de una variable concreta (p.e., porcentaje de ocupación en plazas, que combina plazas ocupadas y plazas disponibles).

Al momento de la estimación de los indicadores, los procedimientos también son harto disímiles entre sí. Continuando con el ejemplo anterior, algunas jurisdicciones estiman el porcentaje de ocupación general en plazas calculando el promedio simple de los porcentajes de ocupación de todos los establecimientos considerados, ya sea porque se releva directamente el porcentaje de ocupación de los establecimientos o porque se lo construye luego de relevar la cantidad de plazas ocupadas y disponibles de cada establecimiento. Otras jurisdicciones, en cambio, obtienen la tasa de ocupación general en plazas sumando la cantidad de plazas ocupadas de todos los establecimientos considerados, y dividiendo el resultado de dicha operación por la cantidad total de plazas disponibles en esos establecimientos. Las mismas diferencias de cálculo se observan cuando se realizan estimaciones en distintos agrupamientos, como ser clase (hotel, apart hotel, b&b, etc.), categoría (estrellas), modalidad (hotelería o para-hotelería) o ubicación (localidad, departamento, región, provincia). La primera forma de cálculo, que estima un promedio más general a partir de promedios parciales, diluye el peso o importancia que cada establecimiento y/o estrato tiene sobre la población total y sobre el agrupamiento que se quiere construir, al no considerar la cantidad de plazas totales disponibles sobre las que se construyó el porcentaje.

Para mayor comprensión del punto anterior, se cita el siguiente ejemplo. Un relevamiento considera dos establecimientos, uno con 200 plazas y otro con 50 plazas; asimismo, el primero declara un 50% de ocupación (100 plazas), mientras que el segundo informa un 70% de ocupación (35 plazas); el primer procedimiento de cálculo obtendría un 60% como porcentaje general de ocupación ((70%+50%)/2), mientras que el segundo estimaría un 54% como porcentaje general de ocupación ((100+35)/(200+50)). Se observa, por lo tanto, que no basta con considerar solo los porcentajes parciales para calcular un porcentaje general de ocupación. Lo adecuado es estimar cuánto representa ese porcentaje sobre las plazas disponibles del total de establecimientos considerados. Por ello, el segundo procedimiento (el cual realiza las estimaciones a partir de valores absolutos) resulta ser el más adecuado.

En otro orden, un inconveniente común a todas las provincias, departamentos y/o municipios, es la **no respuesta** por parte de algunos dueños o responsables de establecimientos. Esto resulta en una cobertura de establecimientos menor a la planeada (ya sea en relevamientos censales como por muestreo). La no respuesta merece especial atención, ya que puede conducir a otro problema denominado **"sesgo de no respuesta"**. Éste consiste en la distorsión, dentro de la muestra o casos alcanzados, del peso que algún/os grupo/s específicos tenía/n originalmente en la población bajo estudio: por ejemplo, si el segmento de hoteles de 1 a 3 estrellas obtiene respuesta de muchos menos establecimientos que los esperados, este grupo quedaría con un peso relativo mucho menor al que tenía en la población bajo estudio, mientras que otros grupos adquirirían, en consecuencia, un peso relativo mayor en relación a la población[^enucestas_alojamientos-7]. En las investigaciones sobre aspectos socio-económicos es muy frecuente que los sujetos que no respondan presenten características similares entre sí, lo que genera un desbalance, que en ocasiones puede ser de gran magnitud, de un estrato o grupo que presentan ciertos rasgos comunes. Dados los efectos que puede causar la no respuesta, es preciso que se evalúe su magnitud e impacto[^enucestas_alojamientos-8] en los resultados y que se generen procesos de imputación de resultados a los establecimientos sin respuesta (o bien, para el total del estrato).

[^enucestas_alojamientos-7]: Cuando un grupo obtiene en la muestra o conjunto de casos un peso menor al que presentaba en la población, éste se encuentra **sub-representado**. Por el contrario, si cuenta con un peso mayor al de la población, el grupo está **sobre-representado**.

[^enucestas_alojamientos-8]: Al respecto, véase apartado 2.9. Procesamiento y análisis de la información.

Por último, merece la pena destacar que en los casos en que se observaron procedimientos de expansión de los resultados obtenidos, estos suelen ser lineales, no respetando el peso o importancia de cada estrato o grupo. En los casos analizados, el mismo consiste en aplicar, por ejemplo, el porcentaje de ocupación en plazas general obtenido en la muestra (o en el conjunto de establecimientos--para los censos) sobre el total de plazas disponibles en todos los establecimientos que conforman el universo de estudio, para luego estimar la cantidad de plazas ocupadas en la población total. Este procedimiento es lineal, en el sentido que realiza una expansión directa, sin evaluar si en los casos efectivamente relevados se produjo un desbalance de los estratos o grupos. En efecto, de haberse producido dicho desbalance, sería necesaria una expansión de los resultados por estrato.

::: {.note} 
Para más información de los informes de resultados, series estadísticas y la metodología, vistá:

[**Informes de prensa en Yvera**](https://www.yvera.tur.ar/estadistica/info/encuesta-de-ocupacion-hotelera-eoh)

[**Data Abierta**](http://datos.yvera.tur.ar/dataset/encuesta-ocupacion-hotelera-parahotelera-eoh)

[**Doc metodológico**](https://www.indec.gob.ar/ftp/cuadros/economia/eoh_aspectos_metodologicos.pdf) **(INDEC)**

:::
