---
title: "Documento Técnico N°2: Encuestas de Ocupación"
subtitle: "Propuestas metodológicas para las encuestas de ocupación en alojamientos turísticos"
author: "Dirección Nacional de Mercados y Estadísticas -  Subsecretaría de Desarrollo Estratégico"
date: "`r format(Sys.Date(), format = '%d de %B de %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Encuestas a establecimientos de alojamiento turístico"
---

# Presentación {.unnumbered}

El presente documento, **Propuestas metodológicas para las encuestas de ocupación en alojamientos turísticos**, se enmarca en el proyecto de [Armonización de las Estadísticas de Turismo en las Provincias](https://armonizacion.yvera.tur.ar//){target="_blank"} de la **Dirección Nacional de Mercados y Estadísticas de la Subsecretaría de Desarrollo Estratégico del Ministerio de Turismo y Deportes**. El objetivo general de este proyecto es contribuir con propuestas metodológicas para los sistemas de estadísticas de turismo provinciales que orienten a producir indicadores provinciales básicos y comparables.

Además de este, se encuentran disponibles una serie de documentos técnicos que abordan otras problemáticas vinculadas a la producción de estadística de turismo:

-   [Documento Técnico \#1](https://dnme-minturdep.github.io/DT1_medicion_turismo/){target="_blank"}: Conceptos y elementos básicos para la medición provincial de los turistas

-   [Documento Técnico \#3](https://dnme-minturdep.github.io/DT3_registros_adminsitrativos/){target="_blank"}: Descripción, análisis y utilización de los Registros Administrativos para la medición del Turismo

-   [Documento Técnico \#4](https://dnme-minturdep.github.io/DT4_perfiles/){target="_blank"}: Propuestas Metodológicas para las Encuestas de Perfil del Visitante

-   [Documento Técnico \#5](https://dnme-minturdep.github.io/DT5_actividad_empleo/){target="_blank"}: Medición de la contribución económica del turismo: actividad y empleo

### Documento Técnico Nº2 - Resumen {.unnumbered}

El propósito general del documento es presentar propuestas metodológicas que puedan ser aplicadas a los relevamientos de alojamientos turísticos en los distintos niveles de interés (municipales, aréas turística, provincias, regiones, etc).

Los objetivos específicos, asimismo, son:

-   Exponer las principales situaciones problemáticasidentificadas en los relevamientos de alojamiento turísticos provinciales y locales.

-   Presentar propuestas y recomendaciones metodológicas aplicables a los relevamientos de alojamientos turísticos, para todas las etapas del estudio, desde su planteamiento inicial hasta la estimación de resultados.

En consecuencia, en el **Capítulo** \@ref(encuesta) se presenta la definición de las encuestas o relevamientos de alojamientos turísticos, así como también las principales situaciones y dificultades identificadas en los diferentes relevamientos provinciales y locales.

En el **Capítulo** \@ref(guiaencuesta) se propone una secuencia lógica de pasos que deberían seguirse para la implementación de una encuesta de alojamientos turísticos.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

knitr::opts_chunk$set(out.width = '100%', fig.align = 'center')
```
